# Brand.create!(name: "HERMES", founder: "Thierry Hermes", country: "France", found_year: "1837", official: "https://www.hermes.com/jp/ja/?utm_source=google_listing&utm_medium=paid&utm_campaign=07hermes&utm_content=0701_S_hermes&gclid=Cj0KCQjwy97qBRDoARIsAITONTJOpPn_t8gaAecJkrJk7lfCKvx3RNPNkKn-JAeIrmrUTSRdvw5A0OIaAiCeEALw_wcB" )
# Brand.create!(name: "FUEGIA 1833")
# Brand.create!(name: "CHANEL")
# Brand.create!(name: "AGONIST")
# Brand.create!(name: "MAD et LEN")
# Brand.create!(name: "DIPTYQUE")
# Brand.create!(name: "ルイ・ヴィトン(LOUIS VUITTON)")
#
#
# Fragrance.create!(name: "ナイルの庭", brand: Brand.find(1), price: 17604, description: "グリーンと植物の匂い。水と砂の匂いからみずみずしさを新たな解釈で表現しました」ジャン=クロード・エレナ" )
# Fragrance.create!(name: "La Cautive", brand: Brand.find(2))
# Fragrance.create!(name: "タムダオ(TAM DAO)", brand: Brand.find(6))
# Fragrance.create!(name: "N°5", brand: Brand.find(3))
# Fragrance.create!(name: "BLUE IN MUSK", brand: Brand.find(5))
# Fragrance.create!(name: "ホワイトライズ(罪のない嘘)", brand: Brand.find(4))
# Fragrance.create!(name: "CHANCE EAU TENDORE", brand: Brand.find(3))
# Fragrance.create!(name: "バニラマーブル(砂糖中毒)", brand: Brand.find(4))
#
# User.create!(name: "admin", email: "admin@example.com", password: "password", admin: true )
# User.create!(name: "aaa", email: "aaa@example.com", password: "aaaaaa" )
# User.create!(name: "bbb", email: "bbb@example.com", password: "bbbbbb" )
# User.create!(name: "ccc", email: "ccc@example.com", password: "cccccc" )
#
# Note.create!(user: User.find(1), fragrance: Fragrance.find(2), content: "test", weather: 0.to_i, humidity: 2.to_i, point: 11.to_i, scene: 4.to_i, want: true)
# Note.create!(user: User.find(2), fragrance: Fragrance.find(8), content: "test", weather: 0.to_i, humidity: 2.to_i, point: 2.to_i, scene: 0.to_i, want: false )
# Note.create!(user: User.find(1), fragrance: Fragrance.find(5), content: "test", weather: 1.to_i, humidity: 0.to_i, point: 2.to_i, scene: 2.to_i, want: true)
# Note.create!(user: User.find(3), fragrance: Fragrance.find(7), content: "test", weather: 0.to_i, humidity: 0.to_i, point: 7.to_i, scene: 4.to_i, want: false )
# Note.create!(user: User.find(2), fragrance: Fragrance.find(2), content: "test", weather: 1.to_i, humidity: 1.to_i, point: 5.to_i, scene: 0.to_i, want: false )
# Note.create!(user: User.find(3), fragrance: Fragrance.find(1), content: "test", weather: 5.to_i, humidity: 2.to_i, point: 2.to_i, scene: 1.to_i, want: false )
# Note.create!(user: User.find(1), fragrance: Fragrance.find(8), content: "test", weather: 0.to_i, humidity: 0.to_i, point: 3.to_i, scene: 0.to_i, want: true)
# Note.create!(user: User.find(2), fragrance: Fragrance.find(2), content: "test", weather: 1.to_i, humidity: 2.to_i, point: 2.to_i, scene: 4.to_i, want: false )
# Note.create!(user: User.find(3), fragrance: Fragrance.find(1), content: "test", weather: 1.to_i, humidity: 1.to_i, point: 2.to_i, scene: 1.to_i, want: false )
# Note.create!(user: User.find(2), fragrance: Fragrance.find(3), content: "test", weather: 2.to_i, humidity: 1.to_i, point: 4.to_i, scene: 0.to_i, want: true)
# Note.create!(user: User.find(3), fragrance: Fragrance.find(4), content: "test", weather: 2.to_i, humidity: 2.to_i, point: 4.to_i, scene: 0.to_i, want: true)
# Note.create!(user: User.find(4), fragrance: Fragrance.find(2), content: "test", weather: 0.to_i, humidity: 2.to_i, point: 11.to_i, scene: 4.to_i, want: true)
# Note.create!(user: User.find(4), fragrance: Fragrance.find(8), content: "test", weather: 0.to_i, humidity: 2.to_i, point: 2.to_i, scene: 0.to_i, want: false )
# Note.create!(user: User.find(3), fragrance: Fragrance.find(5), content: "test", weather: 1.to_i, humidity: 0.to_i, point: 2.to_i, scene: 2.to_i, want: true)
# Note.create!(user: User.find(4), fragrance: Fragrance.find(7), content: "test", weather: 0.to_i, humidity: 0.to_i, point: 7.to_i, scene: 4.to_i, want: false )
# Note.create!(user: User.find(3), fragrance: Fragrance.find(2), content: "test", weather: 1.to_i, humidity: 1.to_i, point: 5.to_i, scene: 0.to_i, want: true )
# Note.create!(user: User.find(1), fragrance: Fragrance.find(7), content: "test", weather: 5.to_i, humidity: 2.to_i, point: 2.to_i, scene: 1.to_i, want: false )
# Note.create!(user: User.find(2), fragrance: Fragrance.find(8), content: "test", weather: 0.to_i, humidity: 0.to_i, point: 3.to_i, scene: 0.to_i, want: true)
# Note.create!(user: User.find(1), fragrance: Fragrance.find(5), content: "test", weather: 5.to_i, humidity: 2.to_i, point: 2.to_i, scene: 1.to_i, want: false )
# Note.create!(user: User.find(2), fragrance: Fragrance.find(3), content: "test", weather: 0.to_i, humidity: 0.to_i, point: 3.to_i, scene: 0.to_i, want: true)

# Perfumer.create!(name: 'ジャン＝クロード・エレナ(Jean-Claude Ellena)', country: 'France', destination_brand_id: Brand.find(1), masterpiece_id: Fragrance.find(1), thought: '香水にはモード（流行）以上のなにかがある。広告にはできない、なにか。香水は時間を横断する。そして身につけられるものである。芸術作品でなければ「時間の外に」生きるものは多くはない。')
# Perfumer.create!(name: 'ニクラス', destination_brand_id: Brand.find(4))
# Perfumer.create!(name: 'クリスティーン', destination_brand_id: Brand.find(4))
# Perfumer.create!(name: 'ジャック・キャヴァリエ・ベルトリュード(Jacques Cavvallier Belletrud)', destination_brand_id: Brand.find(7))
# Perfumer.create!(name: 'ジュリアン・べデル(Julian Bedel)', destination_brand_id: Brand.find(2))
# Perfumer.create!(name: 'オリヴィア・ジャコベッティ(Olivia Giacobetti)')
# Perfumer.create!(name: 'セリーヌ・エレナ')
# Perfumer.create!(name: 'ジャック・ゲラン')
# Perfumer.create!(name: 'エメ・ゲラン')
# Perfumer.create!(name: 'ジャン・ポール・ゲラン')
# Perfumer.create!(name: 'ジャック・ポルジュ', destination_brand_id: Brand.find(3))
# Perfumer.create!(name: 'エドモン・ルドニッカ')
#
# Label.create!(name: '軽い')
# Label.create!(name: '重い')
# Label.create!(name: 'パウダリー')
# Label.create!(name: 'ひんやり')
# Label.create!(name: '柔らかい')
