Brand.create!(name: "HERMES", founder: "Thierry Hermes", country: "France", found_year: "1837", official: "https://www.hermes.com/jp/ja/?utm_source=google_listing&utm_medium=paid&utm_campaign=07hermes&utm_content=0701_S_hermes&gclid=Cj0KCQjwy97qBRDoARIsAITONTJOpPn_t8gaAecJkrJk7lfCKvx3RNPNkKn-JAeIrmrUTSRdvw5A0OIaAiCeEALw_wcB" )
Brand.create!(name: "FUEGIA 1833")
Fragrance.create!(name: "ナイルの庭", brand: Brand.find(1), price: 17604, description: "グリーンと植物の匂い。水と砂の匂いからみずみずしさを新たな解釈で表現しました」ジャン=クロード・エレナ" )
Fragrance.create!(name: "La Cautive", brand: Brand.find(2))
User.create!(name: "aaa", email: "aaa@example.com", password: "aaaaaa", admin: true )
User.create!(name: "bbb", email: "bbbbbb@example.com", password: "bbbbbb" )
Note.create!(user: User.find(1), fragrance: Fragrance.find(2), content: "test")
